POST http://localhost:3000/api/groups/join/831bce58-fc9d-4931-9e8b-cf752fc32607
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdlcmdlcmVncmVnciIsImlkIjoiNjE5Y2Q1MmQtYTFjOS00NGM0LWI0N2UtNjU2ZWRlNWU3MzJjIiwiaWF0IjoxNjA5NTY0MzM1fQ.2caLQsatHFbz8pLuSSPOBj1c0srkGZ2MePYH-qRv2z0