POST http://localhost:3001/api/groups/join/0e767634-a7b2-47f1-92d6-94ea6b171241
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdlcmdlcmVncmVnciIsImlkIjoiNjE5Y2Q1MmQtYTFjOS00NGM0LWI0N2UtNjU2ZWRlNWU3MzJjIiwiaWF0IjoxNjA5NTU3NjU2fQ._bohuKpdvpKC5IGUaURjl2oIho7AaPGNCFKqfKIeiVU